import { Job } from './types'; // Adjust the path to your types file

export const jobsData: Job[] = [
  {
    id: 'e4f8d5a1-9a7c-4c6b-8e1d-3b7c9f8a2e1d',
    job_title: 'Senior Backend Engineer',
    company: 'Innovate Solutions',
    location: {
      city: 'San Francisco',
      state: 'CA',
      country: 'USA',
      is_remote: true,
    },
    seniority_level: 'Senior',
    job_type: 'Full-Time',
    salary_range: {
      min: 150000,
      max: 180000,
      currency: 'USD',
    },
    tech_stack: [
      'Python',
      'Django',
      'PostgreSQL',
      'AWS',
      'Docker',
      'Kubernetes',
    ],
    description:
      'We are seeking a highly skilled Senior Backend Engineer to join our growing team. You will be responsible for designing, developing, and maintaining our core backend services. Experience with microservices architecture is a plus.',
    posted_date: '2025-09-01',
    applicants: 45,
  },
  {
    id: 'a9b1c2d3-4e5f-6a7b-8c9d-0e1f2a3b4c5d',
    job_title: 'Full Stack Developer',
    company: 'Creative Hub',
    location: {
      city: 'New York',
      state: 'NY',
      country: 'USA',
      is_remote: false,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Full-Time',
    salary_range: {
      min: 110000,
      max: 135000,
      currency: 'USD',
    },
    tech_stack: ['JavaScript', 'React', 'Node.js', 'MongoDB', 'Express.js'],
    description:
      'Join our dynamic team to build and maintain both the front-end and back-end of our cutting-edge web applications. We are looking for someone with a passion for clean code and a knack for problem-solving.',
    posted_date: '2025-08-28',
    applicants: 62,
  },
  {
    id: 'f8e7d6c5-b4a3-2c1b-0a9d-8c7b6a5d4e3f',
    job_title: 'UI/UX Designer',
    company: 'Design Forward',
    location: {
      city: 'London',
      country: 'UK',
      is_remote: true,
    },
    seniority_level: 'Junior',
    job_type: 'Full-Time',
    salary_range: null,
    tech_stack: ['Figma', 'Sketch', 'Adobe XD', 'HTML', 'CSS'],
    description:
      "We're looking for a creative UI/UX Designer to help us craft beautiful and intuitive user experiences.",
    posted_date: '2025-09-05',
    applicants: 88,
  },
  {
    id: 'c1a2b3d4-e5f6-a7b8-c9d0-e1f2a3b4c5d6',
    job_title: 'Data Science Intern',
    company: 'Quantum Analytics',
    location: {
      city: 'Austin',
      state: 'TX',
      country: 'USA',
      is_remote: false,
    },
    seniority_level: 'Intern',
    job_type: 'Internship',
    salary_range: {
      min: 25,
      max: 30,
      currency: 'USD_hourly',
    },
    tech_stack: ['Python', 'R', 'SQL', 'Pandas', 'Matplotlib'],
    description:
      'An excellent opportunity for a student to gain hands-on experience in the field of data science. You will assist our senior data scientists with data cleaning and analysis.',
    posted_date: '2025-09-02',
    applicants: 124,
  },
  {
    id: 'd6e5c4b3-a2b1-0c9d-8e7f-6a5b4c3d2e1f',
    job_title: 'Mobile App Developer (iOS)',
    company: 'Global Connect',
    location: {
      city: 'Berlin',
      country: 'Germany',
      is_remote: true,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Full-Time',
    salary_range: {
      min: 75000,
      max: 95000,
      currency: 'EUR',
    },
    tech_stack: ['Swift', 'Xcode', 'SwiftUI', 'RESTful APIs'],
    description:
      'We are seeking a talented iOS developer to join our mobile team. You will work on new features, bug fixes, and performance improvements for our flagship application.',
    posted_date: '2025-09-03',
    applicants: 39,
  },
  {
    id: '8b9a7c6f-5e4d-3c2b-1a09-8f7e6d5c4b3a',
    job_title: 'DevOps Engineer',
    company: 'CloudStream',
    location: {
      city: 'Seattle',
      state: 'WA',
      country: 'USA',
      is_remote: true,
    },
    seniority_level: 'Senior',
    job_type: 'Full-Time',
    salary_range: {
      min: 160000,
      max: 190000,
      currency: 'USD',
    },
    tech_stack: [
      'AWS',
      'Azure',
      'Terraform',
      'Ansible',
      'Jenkins',
      'GitLab CI/CD',
    ],
    description:
      "Bring your expertise in cloud infrastructure and CI/CD to our team. You'll be responsible for automating our deployment pipelines and managing our cloud environments.",
    posted_date: '2025-09-04',
    applicants: 21,
  },
  {
    id: '9d8c7b6a-5f4e-3d2c-1b0a-9e8d7c6b5a4f',
    job_title: 'Junior Front End Developer',
    company: 'Web Spark',
    location: {
      city: 'Boston',
      state: 'MA',
      country: 'USA',
      is_remote: false,
    },
    seniority_level: 'Junior',
    job_type: 'Full-Time',
    salary_range: {
      min: 60000,
      max: 75000,
      currency: 'USD',
    },
    tech_stack: ['HTML', 'CSS', 'JavaScript', 'React', 'Bootstrap'],
    description:
      'An excellent opportunity for an enthusiastic and motivated junior developer to kickstart their career. You will work alongside senior developers on exciting projects.',
    posted_date: '2025-09-01',
    applicants: 115,
  },
  {
    id: '5a4b3c2d-1e0f-9a8b-7c6d-5e4f3a2b1c0d',
    job_title: 'Product Manager Intern',
    company: 'Market Makers Inc.',
    location: {
      city: 'Chicago',
      state: 'IL',
      country: 'USA',
      is_remote: true,
    },
    seniority_level: 'Intern',
    job_type: 'Internship',
    salary_range: {
      min: 20,
      max: 28,
      currency: 'USD_hourly',
    },
    tech_stack: ['Jira', 'Confluence', 'Agile/Scrum'],
    description:
      'Assist our product team in market research, user interviews, and feature planning for our new mobile application.',
    posted_date: '2025-08-30',
    applicants: 98,
  },
  {
    id: '7b6a5d4c-3e2f-1d0c-9b8a-7e6d5c4b3a21',
    job_title: 'Machine Learning Engineer',
    company: 'DeepMind Labs',
    location: {
      city: 'Palo Alto',
      state: 'CA',
      country: 'USA',
      is_remote: false,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Full-Time',
    salary_range: {
      min: 120000,
      max: 150000,
      currency: 'USD',
    },
    tech_stack: ['Python', 'TensorFlow', 'Keras', 'GCP', 'BigQuery'],
    description:
      'We are seeking a talented Machine Learning Engineer to help us develop and deploy cutting-edge AI models. Experience with NLP or computer vision is a plus.',
    posted_date: '2025-09-06',
    applicants: 55,
  },
  {
    id: 'f2e1d0c9-8b7a-6f5e-4d3c-2b1a0f9e8d7c',
    job_title: 'Database Administrator',
    company: 'Data Fortress',
    location: {
      city: 'Dallas',
      state: 'TX',
      country: 'USA',
      is_remote: false,
    },
    seniority_level: 'Senior',
    job_type: 'Full-Time',
    salary_range: {
      min: 100000,
      max: 120000,
      currency: 'USD',
    },
    tech_stack: ['SQL Server', 'MySQL', 'Oracle', 'Data Migration'],
    description:
      'Manage and maintain our critical database systems. You will be responsible for performance tuning, backup, and security.',
    posted_date: '2025-08-25',
    applicants: 32,
  },
  {
    id: 'd0c9b8a7-e6f5-d4c3-b2a1-0e9d8c7b6a5f',
    job_title: 'Quality Assurance Engineer',
    company: 'TestMasters',
    location: {
      city: 'Toronto',
      country: 'Canada',
      is_remote: true,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Full-Time',
    salary_range: {
      min: 80000,
      max: 100000,
      currency: 'CAD',
    },
    tech_stack: ['Selenium', 'Jira', 'JMeter', 'TestRail'],
    description:
      'Ensure the quality of our software products through manual and automated testing. You will work closely with development teams to identify and resolve issues.',
    posted_date: '2025-09-07',
    applicants: 48,
  },
  {
    id: 'f5e4d3c2-b1a0-9c8d-7e6f-5a4b3c2d1e0f',
    job_title: 'Cybersecurity Analyst Intern',
    company: 'SecureNet',
    location: {
      city: 'Washington, D.C.',
      state: 'DC',
      country: 'USA',
      is_remote: false,
    },
    seniority_level: 'Intern',
    job_type: 'Internship',
    salary_range: {
      min: 22,
      max: 28,
      currency: 'USD_hourly',
    },
    tech_stack: ['SIEM', 'Wireshark', 'Nessus'],
    description:
      'Assist our security team with monitoring and incident response. This role is a great way to get started in the cybersecurity field.',
    posted_date: '2025-09-08',
    applicants: 76,
  },
  {
    id: 'a9b8c7d6-e5f4-d3c2-b1a0-9e8d7c6b5a4f',
    job_title: 'Cloud Architect',
    company: 'Nexus Corp',
    location: {
      city: 'Sydney',
      country: 'Australia',
      is_remote: false,
    },
    seniority_level: 'Director',
    job_type: 'Full-Time',
    salary_range: {
      min: 180000,
      max: 220000,
      currency: 'AUD',
    },
    tech_stack: ['AWS', 'Azure', 'GCP', 'Enterprise Architecture'],
    description:
      "Design and oversee the implementation of our company's cloud computing strategy. This is a leadership role requiring deep technical and business acumen.",
    posted_date: '2025-08-29',
    applicants: 12,
  },
  {
    id: 'c3d2e1f0-9a8b-7c6d-5e4f-3a2b1c0d9e8f',
    job_title: 'Project Manager',
    company: 'Agile Projects Inc.',
    location: {
      city: 'Denver',
      state: 'CO',
      country: 'USA',
      is_remote: true,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Full-Time',
    salary_range: {
      min: 95000,
      max: 115000,
      currency: 'USD',
    },
    tech_stack: ['Jira', 'Confluence', 'Agile', 'Scrum'],
    description:
      'Manage and deliver technology projects on time and within budget. You will work closely with stakeholders to define project scope, goals, and deliverables.',
    posted_date: '2025-09-04',
    applicants: 38,
  },
  {
    id: 'e7d6c5b4-a3b2-c1d0-9e8f-7a6b5c4d3e21',
    job_title: 'Game Developer',
    company: 'Pixel Play Studios',
    location: {
      city: 'Tokyo',
      country: 'Japan',
      is_remote: false,
    },
    seniority_level: 'Junior',
    job_type: 'Full-Time',
    salary_range: {
      min: 4000000,
      max: 5500000,
      currency: 'JPY',
    },
    tech_stack: ['Unity', 'C#', 'Unreal Engine', 'C++'],
    description:
      'Join our team of creative game developers to build the next big hit. You will contribute to all aspects of game development, from design to implementation.',
    posted_date: '2025-08-27',
    applicants: 91,
  },
  {
    id: '9b8a7c6d-5e4f-3d2c-1b0a-9e8d7c6b5a4f',
    job_title: 'Technical Writer',
    company: 'DocuGenius',
    location: {
      city: 'Remote',
      is_remote: true,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Full-Time',
    salary_range: {
      min: 85000,
      max: 100000,
      currency: 'USD',
    },
    tech_stack: ['Markdown', 'Git', 'Sphinx', 'API Documentation'],
    description:
      'We are seeking a Technical Writer to create clear and concise documentation for our software products. You will work closely with engineers to ensure accuracy and clarity.',
    posted_date: '2025-09-08',
    applicants: 27,
  },
  {
    id: '1c2b3a4d-5e6f-7c8d-9e0f-1a2b3c4d5e6f',
    job_title: 'UX Researcher',
    company: 'User Insights',
    location: {
      city: 'San Francisco',
      state: 'CA',
      country: 'USA',
      is_remote: false,
    },
    seniority_level: 'Senior',
    job_type: 'Full-Time',
    salary_range: {
      min: 145000,
      max: 170000,
      currency: 'USD',
    },
    tech_stack: [
      'User Interviews',
      'Usability Testing',
      'Survey Design',
      'Data Analysis',
    ],
    description:
      'Lead user research initiatives to inform our product strategy and design. You will be responsible for planning and executing research studies and communicating findings to the team.',
    posted_date: '2025-08-29',
    applicants: 19,
  },
  {
    id: '2d1c3b4a-5f6e-7d8c-9b0a-1e2f3d4c5b6a',
    job_title: 'Systems Administrator',
    company: 'Global Networks',
    location: {
      city: 'Dubai',
      country: 'UAE',
      is_remote: false,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Full-Time',
    salary_range: {
      min: 150000,
      max: 200000,
      currency: 'AED',
    },
    tech_stack: ['Linux', 'Windows Server', 'VMware', 'Active Directory'],
    description:
      'Manage and maintain our IT infrastructure, including servers, networks, and storage systems. You will be responsible for system uptime, security, and performance.',
    posted_date: '2025-09-03',
    applicants: 42,
  },
  {
    id: '3e2d1c4b-5a6f-7b8c-9d0e-1f2a3b4c5d6e',
    job_title: 'Data Analyst Intern',
    company: 'Insights Corp',
    location: {
      city: 'Singapore',
      country: 'Singapore',
      is_remote: true,
    },
    seniority_level: 'Intern',
    job_type: 'Internship',
    salary_range: {
      min: 15,
      max: 20,
      currency: 'SGD_hourly',
    },
    tech_stack: ['SQL', 'Excel', 'Tableau', 'Python'],
    description:
      'We are looking for a motivated Data Analyst Intern to join our team. You will be responsible for collecting, cleaning, and analyzing data to support business decisions.',
    posted_date: '2025-09-05',
    applicants: 156,
  },
  {
    id: '4f3e2d1c-5a6b-7c8d-9e0f-1a2b3c4d5e6f',
    job_title: 'Site Reliability Engineer',
    company: 'Resilience Labs',
    location: {
      city: 'Remote',
      is_remote: true,
    },
    seniority_level: 'Senior',
    job_type: 'Full-Time',
    salary_range: {
      min: 155000,
      max: 195000,
      currency: 'USD',
    },
    tech_stack: ['Kubernetes', 'Prometheus', 'Grafana', 'Golang', 'Python'],
    description:
      'Ensure the reliability and scalability of our production systems. You will work on designing and implementing monitoring, alerting, and incident response systems.',
    posted_date: '2025-09-07',
    applicants: 31,
  },
  {
    id: '5a4b3c2d-1e0f-9a8b-7c6d-5e4f3a2b1c0d',
    job_title: 'Mobile App Developer (Android)',
    company: 'Global Connect',
    location: {
      city: 'Berlin',
      country: 'Germany',
      is_remote: true,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Full-Time',
    salary_range: {
      min: 75000,
      max: 95000,
      currency: 'EUR',
    },
    tech_stack: ['Kotlin', 'Android Studio', 'Java', 'RESTful APIs'],
    description:
      'We are seeking a talented Android developer to join our mobile team. You will work on new features, bug fixes, and performance improvements for our flagship application.',
    posted_date: '2025-09-03',
    applicants: 47,
  },
  {
    id: '6c5b4a3d-2e1f-0a9d-8c7b-6a5d4e3f2c1b',
    job_title: 'Network Engineer',
    company: 'Data Fortress',
    location: {
      city: 'London',
      country: 'UK',
      is_remote: false,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Full-Time',
    salary_range: {
      min: 60000,
      max: 80000,
      currency: 'GBP',
    },
    tech_stack: ['Cisco', 'Juniper', 'TCP/IP', 'Routing', 'Firewalls'],
    description:
      "Design, implement, and manage our company's network infrastructure. You will be responsible for network performance, security, and reliability.",
    posted_date: '2025-09-06',
    applicants: 25,
  },
  {
    id: '7d8c9b0a-1e2f-3d4c-5b6a-7f8e9d0c1b2a',
    job_title: 'Salesforce Developer',
    company: 'CloudSolutions Inc.',
    location: {
      city: 'Atlanta',
      state: 'GA',
      country: 'USA',
      is_remote: true,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Full-Time',
    salary_range: {
      min: 105000,
      max: 125000,
      currency: 'USD',
    },
    tech_stack: [
      'Salesforce',
      'Apex',
      'Visualforce',
      'Lightning Web Components',
    ],
    description:
      'We are seeking an experienced Salesforce Developer to customize and build new features on the Salesforce platform. You will work with business analysts to deliver solutions.',
    posted_date: '2025-09-01',
    applicants: 41,
  },
  {
    id: '8e9f0a1b-2c3d-4e5f-6a7b-8c9d0e1f2a3b',
    job_title: 'IT Support Technician',
    company: 'Tech Help',
    location: {
      city: 'Phoenix',
      state: 'AZ',
      country: 'USA',
      is_remote: false,
    },
    seniority_level: 'Junior',
    job_type: 'Full-Time',
    salary_range: {
      min: 50000,
      max: 65000,
      currency: 'USD',
    },
    tech_stack: ['Windows', 'macOS', 'Troubleshooting', 'Ticketing Systems'],
    description:
      'Provide first-line technical support to our employees. You will resolve hardware and software issues and maintain IT equipment.',
    posted_date: '2025-09-04',
    applicants: 68,
  },
  {
    id: '9a0b1c2d-3e4f-5a6b-7c8d-9e0f1a2b3c4d',
    job_title: 'Full Stack Intern',
    company: 'Future Tech',
    location: {
      city: 'Remote',
      is_remote: true,
    },
    seniority_level: 'Intern',
    job_type: 'Internship',
    salary_range: {
      min: 20,
      max: 25,
      currency: 'USD_hourly',
    },
    tech_stack: ['JavaScript', 'React', 'Express.js'],
    description:
      'A paid internship for students interested in full-stack development. You will contribute to real-world projects and be mentored by senior engineers.',
    posted_date: '2025-09-02',
    applicants: 105,
  },
];
