import { Job } from './types'; // Adjust the path to your types file

export const jobsData: Job[] = [
  {
    id: 'e4f8d5a1-9a7c-4c6b-8e1d-3b7c9f8a2e1d',
    job_title: 'Senior Java Backend Developer',
    company: 'Tech Mahindra',
    location: {
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      is_remote: false,
    },
    seniority_level: 'Senior',
    job_type: 'Internship',
    salary_range: {
      min: 1800000,
      max: 2500000,
      currency: 'INR',
    },
    tech_stack: [
      'Java',
      'Spring Boot',
      'Hibernate',
      'Microservices',
      'AWS',
      'Docker',
    ],
    description:
      'We are seeking a highly skilled Senior Java Backend Developer to design, develop, and maintain robust backend services. Strong experience with Spring Boot and microservices architecture is essential.',
    posted_date: '2025-09-01',
    applicants: 52,
  },
  {
    id: 'a9b1c2d3-4e5f-6a7b-8c9d-0e1f2a3b4c5d',
    job_title: 'Full Stack Developer',
    company: 'Infosys',
    location: {
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
      is_remote: false,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Internship',
    salary_range: {
      min: 800000,
      max: 1200000,
      currency: 'INR',
    },
    tech_stack: ['JavaScript', 'Angular', 'Node.js', 'Express.js', 'MongoDB'],
    description:
      'Join our dynamic team to build and maintain both the front-end and back-end of our cutting-edge web applications. We are looking for someone with a passion for clean code.',
    posted_date: '2025-08-28',
    applicants: 78,
  },
  {
    id: 'f8e7d6c5-b4a3-2c1b-0a9d-8c7b6a5d4e3f',
    job_title: 'UX/UI Designer',
    company: 'Wipro',
    location: {
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      is_remote: true,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Internship',
    salary_range: {
      min: 750000,
      max: 1000000,
      currency: 'INR',
    },
    tech_stack: ['Figma', 'Sketch', 'Adobe XD', 'User Research'],
    description:
      "We're looking for a creative UI/UX Designer to help us craft beautiful and intuitive user experiences for our enterprise software solutions.",
    posted_date: '2025-09-05',
    applicants: 94,
  },
  {
    id: 'c1a2b3d4-e5f6-a7b8-c9d0-e1f2a3b4c5d6',
    job_title: 'Data Scientist Intern',
    company: 'TCS (Tata Consultancy Services)',
    location: {
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
      is_remote: false,
    },
    seniority_level: 'Intern',
    job_type: 'Internship',
    salary_range: {
      min: 25000,
      max: 35000,
      currency: 'INR_monthly',
    },
    tech_stack: ['Python', 'R', 'SQL', 'Pandas', 'SciKit-Learn'],
    description:
      'An excellent opportunity for a student to gain hands-on experience in the field of data science. You will assist our senior data scientists with data cleaning and analysis.',
    posted_date: '2025-09-02',
    applicants: 156,
  },
  {
    id: 'd6e5c4b3-a2b1-0c9d-8e7f-6a5b4c3d2e1f',
    job_title: 'Mobile App Developer (Android)',
    company: "Byju's",
    location: {
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      is_remote: true,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Internship',
    salary_range: {
      min: 900000,
      max: 1400000,
      currency: 'INR',
    },
    tech_stack: ['Kotlin', 'Android Studio', 'Java', 'RESTful APIs'],
    description:
      'We are seeking a talented Android developer to join our mobile team. You will work on new features, bug fixes, and performance improvements for our educational application.',
    posted_date: '2025-09-03',
    applicants: 67,
  },
  {
    id: '8b9a7c6f-5e4d-3c2b-1a09-8f7e6d5c4b3a',
    job_title: 'DevOps Engineer',
    company: 'Paytm',
    location: {
      city: 'Noida',
      state: 'Uttar Pradesh',
      country: 'India',
      is_remote: false,
    },
    seniority_level: 'Senior',
    job_type: 'Internship',
    salary_range: {
      min: 1700000,
      max: 2300000,
      currency: 'INR',
    },
    tech_stack: ['AWS', 'Docker', 'Kubernetes', 'Jenkins', 'Ansible', 'Git'],
    description:
      "Bring your expertise in cloud infrastructure and CI/CD to our team. You'll be responsible for automating our deployment pipelines and managing our cloud environments.",
    posted_date: '2025-09-04',
    applicants: 38,
  },
  {
    id: '9d8c7b6a-5f4e-3d2c-1b0a-9e8d7c6b5a4f',
    job_title: 'Junior Front End Developer',
    company: 'Zoho',
    location: {
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      is_remote: false,
    },
    seniority_level: 'Junior',
    job_type: 'Internship',
    salary_range: {
      min: 450000,
      max: 700000,
      currency: 'INR',
    },
    tech_stack: ['HTML', 'CSS', 'JavaScript', 'React', 'Redux'],
    description:
      'An excellent opportunity for an enthusiastic and motivated junior developer to kickstart their career. You will work alongside senior developers on exciting projects.',
    posted_date: '2025-09-01',
    applicants: 112,
  },
  {
    id: '5b4b3c2d-1e0f-9a8b-7c6d-5d4f8a2b3c0d',
    job_title: 'Business Analyst Intern',
    company: 'Deloitte',
    location: {
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      is_remote: false,
    },
    seniority_level: 'Intern',
    job_type: 'Internship',
    salary_range: {
      min: 20000,
      max: 30000,
      currency: 'INR_monthly',
    },
    tech_stack: ['SQL', 'Excel', 'Power BI', 'Business Intelligence'],
    description:
      'Assist our consulting team in analyzing business processes and requirements. This role is a great way to get started in the world of business and tech.',
    posted_date: '2025-08-30',
    applicants: 134,
  },
  {
    id: '7b6a5d4c-3e2f-1d0c-9b8a-7e6d5c4b3a21',
    job_title: 'Machine Learning Engineer',
    company: 'Flipkart',
    location: {
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      is_remote: false,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Internship',
    salary_range: {
      min: 1400000,
      max: 1800000,
      currency: 'INR',
    },
    tech_stack: ['Python', 'PyTorch', 'TensorFlow', 'Spark', 'GCP'],
    description:
      'We are seeking a talented Machine Learning Engineer to help us develop and deploy cutting-edge AI models for our e-commerce platform. Experience with NLP or computer vision is a plus.',
    posted_date: '2025-09-06',
    applicants: 45,
  },
  {
    id: 'f2e1d0c9-8b7a-6f5e-4d3c-2b1a0f9e8d7c',
    job_title: 'Cloud Architect',
    company: 'Amazon Web Services (AWS)',
    location: {
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
      is_remote: false,
    },
    seniority_level: 'Senior',
    job_type: 'Internship',
    salary_range: {
      min: 2500000,
      max: 3500000,
      currency: 'INR',
    },
    tech_stack: [
      'AWS',
      'Azure',
      'GCP',
      'Cloud Strategy',
      'Solutions Architecture',
    ],
    description:
      'Design and oversee the implementation of large-scale cloud computing solutions for our clients. This is a leadership role requiring deep technical expertise.',
    posted_date: '2025-08-25',
    applicants: 21,
  },
  {
    id: 'd0c9b8a7-e6f5-d4c3-b2a1-0e9d8c7b6a5f',
    job_title: 'Quality Assurance Engineer',
    company: 'HCL Technologies',
    location: {
      city: 'Noida',
      state: 'Uttar Pradesh',
      country: 'India',
      is_remote: true,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Internship',
    salary_range: {
      min: 700000,
      max: 1000000,
      currency: 'INR',
    },
    tech_stack: ['Selenium', 'Jira', 'TestNG', 'API Testing'],
    description:
      'Ensure the quality of our software products through manual and automated testing. You will work closely with development teams to identify and resolve issues.',
    posted_date: '2025-09-07',
    applicants: 64,
  },
  {
    id: 'f5e4d3c2-b1a0-9c8d-7e6f-5a4b3c2d1e0f',
    job_title: 'Junior Cybersecurity Analyst',
    company: 'Tata Communications',
    location: {
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      is_remote: false,
    },
    seniority_level: 'Junior',
    job_type: 'Internship',
    salary_range: {
      min: 600000,
      max: 850000,
      currency: 'INR',
    },
    tech_stack: ['SIEM', 'Wireshark', 'Penetration Testing'],
    description:
      'Help us protect our digital assets from threats. You will be responsible for monitoring security systems, responding to incidents, and conducting vulnerability assessments.',
    posted_date: '2025-09-08',
    applicants: 81,
  },
  {
    id: 'a9b8c7d6-e5f4-d3c2-b1a0-9e8d7c6b5a4f',
    job_title: 'Product Manager',
    company: 'Swiggy',
    location: {
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      is_remote: false,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Internship',
    salary_range: {
      min: 1500000,
      max: 2200000,
      currency: 'INR',
    },
    tech_stack: ['Jira', 'Confluence', 'Agile/Scrum', 'Market Research'],
    description:
      'Lead the strategy and execution of our product roadmap for our food delivery platform. You will be the voice of the customer and work cross-functionally with engineering, design, and marketing teams.',
    posted_date: '2025-08-29',
    applicants: 41,
  },
  {
    id: 'c3d2e1f0-9a8b-7c6d-5e4f-3a2b1c0d9e8f',
    job_title: 'Project Manager',
    company: 'L&T Infotech',
    location: {
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      is_remote: true,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Internship',
    salary_range: {
      min: 1100000,
      max: 1600000,
      currency: 'INR',
    },
    tech_stack: ['PMP', 'Agile', 'Scrum', 'Risk Management'],
    description:
      'Manage and deliver technology projects on time and within budget. You will work closely with stakeholders to define project scope, goals, and deliverables.',
    posted_date: '2025-09-04',
    applicants: 38,
  },
  {
    id: 'e7d6c5b4-a3b2-c1d0-9e8f-7a6b5c4d3e21',
    job_title: 'Data Analyst',
    company: 'Accenture',
    location: {
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
      is_remote: false,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Internship',
    salary_range: {
      min: 850000,
      max: 1100000,
      currency: 'INR',
    },
    tech_stack: ['SQL', 'Tableau', 'Python', 'Power BI', 'Data Visualization'],
    description:
      'We are seeking a talented Data Analyst to join our team. You will be responsible for collecting, cleaning, and analyzing data to support business decisions for our clients.',
    posted_date: '2025-08-27',
    applicants: 72,
  },
  {
    id: '9b8a7c6d-5e4f-3d2c-1b0a-9e8d7c6b5a4f',
    job_title: 'Technical Writer',
    company: 'Capgemini',
    location: {
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      is_remote: true,
    },
    seniority_level: 'Junior',
    job_type: 'Internship',
    salary_range: {
      min: 500000,
      max: 750000,
      currency: 'INR',
    },
    tech_stack: ['Markdown', 'Git', 'API Documentation'],
    description:
      'We are seeking a Technical Writer to create clear and concise documentation for our software products. You will work closely with engineers to ensure accuracy and clarity.',
    posted_date: '2025-09-08',
    applicants: 60,
  },
  {
    id: '1c2b3a4d-5e6f-7c8d-9e0f-1a2b3c4d5e6f',
    job_title: 'UX Researcher',
    company: 'Zomato',
    location: {
      city: 'Gurugram',
      state: 'Haryana',
      country: 'India',
      is_remote: false,
    },
    seniority_level: 'Senior',
    job_type: 'Internship',
    salary_range: {
      min: 1700000,
      max: 2400000,
      currency: 'INR',
    },
    tech_stack: [
      'User Interviews',
      'Usability Testing',
      'Survey Design',
      'Data Analysis',
    ],
    description:
      'Lead user research initiatives to inform our product strategy and design for our food delivery and dining platform. You will be responsible for planning and executing research studies and communicating findings to the team.',
    posted_date: '2025-08-29',
    applicants: 27,
  },
  {
    id: '2d1c3b4a-5f6e-7d8c-9b0a-1e2f3d4c5b6a',
    job_title: 'Systems Administrator',
    company: 'Cognizant',
    location: {
      city: 'Kolkata',
      state: 'West Bengal',
      country: 'India',
      is_remote: false,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Internship',
    salary_range: {
      min: 650000,
      max: 900000,
      currency: 'INR',
    },
    tech_stack: ['Linux', 'Windows Server', 'VMware', 'Active Directory'],
    description:
      'Manage and maintain our IT infrastructure, including servers, networks, and storage systems. You will be responsible for system uptime, security, and performance.',
    posted_date: '2025-09-03',
    applicants: 42,
  },
  {
    id: '3e2d1c4b-5a6f-7b8c-9d0e-1f2a3b4c5d6e',
    job_title: 'Data Analyst Intern',
    company: 'Udaan',
    location: {
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      is_remote: false,
    },
    seniority_level: 'Intern',
    job_type: 'Internship',
    salary_range: {
      min: 30000,
      max: 40000,
      currency: 'INR_monthly',
    },
    tech_stack: ['SQL', 'Excel', 'Python', 'Pandas'],
    description:
      'We are looking for a motivated Data Analyst Intern to join our team. You will be responsible for collecting, cleaning, and analyzing data to support business decisions.',
    posted_date: '2025-09-05',
    applicants: 122,
  },
  {
    id: '4f3e2d1c-5a6b-7c8d-9e0f-1a2b3c4d5e6f',
    job_title: 'Site Reliability Engineer',
    company: 'Cred',
    location: {
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      is_remote: true,
    },
    seniority_level: 'Senior',
    job_type: 'Internship',
    salary_range: {
      min: 2000000,
      max: 3000000,
      currency: 'INR',
    },
    tech_stack: ['Kubernetes', 'Prometheus', 'Golang', 'Python'],
    description:
      'Ensure the reliability and scalability of our production systems. You will work on designing and implementing monitoring, alerting, and incident response systems.',
    posted_date: '2025-09-07',
    applicants: 35,
  },
  {
    id: '5c4b3c2d-1e0f-9a8b-7c6d-5e4f5a2b1c0d',
    job_title: 'Mobile App Developer (iOS)',
    company: 'Myntra',
    location: {
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      is_remote: false,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Internship',
    salary_range: {
      min: 1200000,
      max: 1800000,
      currency: 'INR',
    },
    tech_stack: ['Swift', 'Xcode', 'SwiftUI', 'RESTful APIs'],
    description:
      'We are seeking a talented iOS developer to join our mobile team. You will work on new features, bug fixes, and performance improvements for our fashion e-commerce application.',
    posted_date: '2025-09-03',
    applicants: 47,
  },
  {
    id: '6c5b4a3d-2e1f-0a9d-8c7b-6a5d4e3f2c1b',
    job_title: 'Network Engineer',
    company: 'Cisco',
    location: {
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      is_remote: false,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Internship',
    salary_range: {
      min: 900000,
      max: 1300000,
      currency: 'INR',
    },
    tech_stack: ['Cisco', 'Juniper', 'TCP/IP', 'Routing', 'Firewalls'],
    description:
      "Design, implement, and manage our company's network infrastructure. You will be responsible for network performance, security, and reliability.",
    posted_date: '2025-09-06',
    applicants: 25,
  },
  {
    id: '7d8c9b0a-1e2f-3d4c-5b6a-7f8e9d0c1b2a',
    job_title: 'Salesforce Developer',
    company: 'Infosys',
    location: {
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
      is_remote: false,
    },
    seniority_level: 'Mid-Level',
    job_type: 'Internship',
    salary_range: {
      min: 1050000,
      max: 1450000,
      currency: 'INR',
    },
    tech_stack: [
      'Salesforce',
      'Apex',
      'Visualforce',
      'Lightning Web Components',
    ],
    description:
      'We are seeking an experienced Salesforce Developer to customize and build new features on the Salesforce platform. You will work with business analysts to deliver solutions.',
    posted_date: '2025-09-01',
    applicants: 41,
  },
  {
    id: '8e9f0a1b-2c3d-4e5f-6a7b-8c9d0e1f2a3b',
    job_title: 'IT Support Technician',
    company: 'Wipro',
    location: {
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      is_remote: false,
    },
    seniority_level: 'Junior',
    job_type: 'Internship',
    salary_range: {
      min: 350000,
      max: 500000,
      currency: 'INR',
    },
    tech_stack: ['Windows', 'macOS', 'Troubleshooting', 'Ticketing Systems'],
    description:
      'Provide first-line technical support to our employees. You will resolve hardware and software issues and maintain IT equipment.',
    posted_date: '2025-09-04',
    applicants: 68,
  },
  {
    id: '9a0b1c2d-3e4f-5a6b-7c8d-9e0f1a2b3c4d',
    job_title: 'Full Stack Intern',
    company: 'Dream11',
    location: {
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      is_remote: false,
    },
    seniority_level: 'Intern',
    job_type: 'Internship',
    salary_range: {
      min: 30000,
      max: 45000,
      currency: 'INR_monthly',
    },
    tech_stack: ['JavaScript', 'React', 'Node.js', 'MongoDB'],
    description:
      "A paid internship for students interested in full-stack development. You will contribute to real-world projects and be mentored by senior engineers at India's leading fantasy sports platform.",
    posted_date: '2025-09-02',
    applicants: 105,
  },
];
